#!/bin/bash

TARGET="$1"
FEDORA_MAJOR_VERSION="$2"
KERNEL_FLAVOR="fsync"
REPOS=("fsync-kernel" "akmods" "akmods-extra" "akmods-nvidia")

set -xeu pipefail

declare -A repo_tags

get_tags() {
repo=$1
if [[ "$repo" == "fsync-kernel" ]]; then
    # fsync-kernel uses the format without the initial flavor in the tag
    skopeo list-tags docker://ghcr.io/ublue-os/${repo} | jq -r '.Tags[]' \
    | grep "^${FEDORA_MAJOR_VERSION}-[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\..*\.fc${FEDORA_MAJOR_VERSION}\.x86_64"
else
    # Other repos use the format with the flavor in the tag
    skopeo list-tags docker://ghcr.io/ublue-os/${repo} | jq -r '.Tags[]' \
    | grep "^${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION}-[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\..*\.fc${FEDORA_MAJOR_VERSION}\.x86_64"
fi
}

for repo in "${REPOS[@]}"; do
  tags=$(get_tags "$repo")
  repo_tags[$repo]="$tags"
done

extract_full_version() {
  echo "$1" | cut -d'-' -f2,3
}

common_versions=($(echo "${repo_tags[fsync-kernel]}" | while read -r tag; do
  full_version=$(extract_full_version "$tag")

  if grep -q "$full_version" <<< "${repo_tags[akmods]}" && \
      grep -q "$full_version" <<< "${repo_tags[akmods-extra]}" && \
      grep -q "$full_version" <<< "${repo_tags[akmods-nvidia]}"; then
      echo "$full_version"
  fi
done | sort -V))

if [ -n "${common_versions[-1]}" ]; then
  podman build . --target "$TARGET" --build-arg KERNEL_VERSION="${common_versions[-1]}"
else
  exit 1
fi


